name: Block Directory.Build.props changes on Develop

# ทำงานเมื่อมี PR ไปยัง branch develop
on:
  pull_request:
    branches:
      - origin/Develop
    paths:
      - 'Directory.Build.props'

jobs:
  block-change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prevent Directory.Build.props modification
        run: |
          # ตรวจสอบไฟล์ที่แก้ใน PR
          if git diff --name-only origin/${{ github.base_ref }} | grep -q 'Directory.Build.props'; then
            echo "❌ Directory.Build.props cannot be changed in PR to develop!"
            exit 1
          fi
