name: Block Directory.Build.props changes on develop

on:
  pull_request:
    branches:
      - develop

jobs:
  block-change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # fetch ประวัติทั้งหมด

      - name: Check Directory.Build.props
        run: |
          echo "Checking Directory.Build.props changes..."
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "Changed files: $CHANGED_FILES"
          if echo "$CHANGED_FILES" | grep -q 'Directory.Build.props'; then
            echo "❌ Directory.Build.props cannot be changed in PR to develop!"
            exit 1
          fi
