name: Block Directory.Build.props changes on develop

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'Directory.Build.props'

jobs:
  block-change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Prevent Directory.Build.props modification
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'Directory.Build.props'; then
            echo "❌ Directory.Build.props cannot be changed in PR to develop!"
            exit 1
          fi
